# SPDX-License-Identifier: GPL-2.0+
#
# Copyright (C) 2017 Andes Technology Corporation.
# Rick Chen, Andes Technology Corporation <rick@andestech.com>

obj-$(CONFIG_TARGET_ANDES25_AE350)	:= andes25-ae350.o
obj-$(CONFIG_TARGET_ANDES45_AE350)	:= andes45-ae350.o
